import { PrismaClient, Brand, Category } from '../../generated/prisma/client';

export async function seedProducts(
  prisma: PrismaClient,
  brands: Brand[],
  children: Category[],
  parents: Category[],
) {
  // brands index: 0=Apple, 1=Samsung, 2=Sony, 4=Dell, 5=HP, 6=Lenovo, 7=ASUS,
  //               9=JBL, 10=Logitech, 11=Razer, 12=Microsoft, 13=Google, 14=Anker,
  //               16=Canon, 18=GoPro, 19=Xiaomi
  // children: 0=android, 1=iphones, 2=gaming-laptops, 3=business-laptops,
  //           4=headphones, 5=earbuds, 6=dslr, 7=action-cameras, 8=chargers,
  //           9=gaming-keyboards, 10=gaming-mice, 11=smart-speakers
  const products = await Promise.all([
    prisma.product.upsert({
      where: { slug: 'iphone-15-pro' },
      update: {},
      create: {
        name: 'iPhone 15 Pro',
        slug: 'iphone-15-pro',
        sku: 'APPL-IP15P-001',
        description: 'The most powerful iPhone ever with A17 Pro chip.',
        shortDescription: 'A17 Pro chip, titanium design, 48MP camera system.',
        price: 999.99,
        comparePrice: 1099.99,
        costPrice: 700.0,
        stock: 150,
        categoryId: children[1].id,
        brandId: brands[0].id,
        status: 'ACTIVE',
        isFeatured: true,
        publishedAt: new Date(),
      },
    }),
    prisma.product.upsert({
      where: { slug: 'samsung-galaxy-s24-ultra' },
      update: {},
      create: {
        name: 'Samsung Galaxy S24 Ultra',
        slug: 'samsung-galaxy-s24-ultra',
        sku: 'SAMS-S24U-001',
        description: 'The ultimate Galaxy experience with S Pen.',
        shortDescription: '200MP camera, Snapdragon 8 Gen 3, 5000mAh.',
        price: 1199.99,
        comparePrice: 1299.99,
        costPrice: 850.0,
        stock: 120,
        categoryId: children[0].id,
        brandId: brands[1].id,
        status: 'ACTIVE',
        isFeatured: true,
        publishedAt: new Date(),
      },
    }),
    prisma.product.upsert({
      where: { slug: 'sony-wh-1000xm5' },
      update: {},
      create: {
        name: 'Sony WH-1000XM5',
        slug: 'sony-wh-1000xm5',
        sku: 'SONY-WH5-001',
        description: 'Industry-leading noise canceling headphones.',
        shortDescription: 'Best-in-class noise cancellation, 30hr battery.',
        price: 349.99,
        comparePrice: 399.99,
        costPrice: 200.0,
        stock: 200,
        categoryId: children[4].id,
        brandId: brands[2].id,
        status: 'ACTIVE',
        isFeatured: true,
        publishedAt: new Date(),
      },
    }),
    prisma.product.upsert({
      where: { slug: 'macbook-pro-16-m3' },
      update: {},
      create: {
        name: 'MacBook Pro 16" M3 Pro',
        slug: 'macbook-pro-16-m3',
        sku: 'APPL-MBP16-001',
        description: 'Supercharged by M3 Pro for pros who push boundaries.',
        shortDescription:
          'M3 Pro chip, Liquid Retina XDR display, 18hr battery.',
        price: 2499.99,
        comparePrice: 2699.99,
        costPrice: 1800.0,
        stock: 80,
        categoryId: children[2].id,
        brandId: brands[0].id,
        status: 'ACTIVE',
        isFeatured: true,
        publishedAt: new Date(),
      },
    }),
    prisma.product.upsert({
      where: { slug: 'dell-xps-15' },
      update: {},
      create: {
        name: 'Dell XPS 15 OLED',
        slug: 'dell-xps-15',
        sku: 'DELL-XPS15-001',
        description: 'Premium 15-inch laptop with OLED display.',
        shortDescription: 'Intel Core i9, NVIDIA RTX 4070, 3.5K OLED touch.',
        price: 1999.99,
        comparePrice: 2199.99,
        costPrice: 1400.0,
        stock: 60,
        categoryId: children[3].id,
        brandId: brands[4].id,
        status: 'ACTIVE',
        publishedAt: new Date(),
      },
    }),
    prisma.product.upsert({
      where: { slug: 'logitech-mx-master-3s' },
      update: {},
      create: {
        name: 'Logitech MX Master 3S',
        slug: 'logitech-mx-master-3s',
        sku: 'LOGI-MXM3S-001',
        description: 'Advanced wireless mouse for creators.',
        shortDescription: '8K DPI sensor, quiet clicks, USB-C charging.',
        price: 99.99,
        comparePrice: 119.99,
        costPrice: 50.0,
        stock: 500,
        categoryId: parents[4].id,
        brandId: brands[10].id,
        status: 'ACTIVE',
        publishedAt: new Date(),
      },
    }),
    prisma.product.upsert({
      where: { slug: 'razer-blackwidow-v4' },
      update: {},
      create: {
        name: 'Razer BlackWidow V4 Pro',
        slug: 'razer-blackwidow-v4',
        sku: 'RAZR-BWV4-001',
        description: 'Ultimate gaming keyboard with Razer Chroma RGB.',
        shortDescription: 'Razer Green switches, wireless, per-key RGB.',
        price: 229.99,
        comparePrice: 249.99,
        costPrice: 130.0,
        stock: 150,
        categoryId: children[9].id,
        brandId: brands[11].id,
        status: 'ACTIVE',
        publishedAt: new Date(),
      },
    }),
    prisma.product.upsert({
      where: { slug: 'apple-airpods-pro-2' },
      update: {},
      create: {
        name: 'Apple AirPods Pro (2nd Gen)',
        slug: 'apple-airpods-pro-2',
        sku: 'APPL-APP2-001',
        description: 'Active Noise Cancellation, Adaptive Transparency.',
        shortDescription: 'H2 chip, 6hr ANC battery, MagSafe case.',
        price: 249.99,
        comparePrice: 279.99,
        costPrice: 150.0,
        stock: 300,
        categoryId: children[5].id,
        brandId: brands[0].id,
        status: 'ACTIVE',
        isFeatured: true,
        publishedAt: new Date(),
      },
    }),
    prisma.product.upsert({
      where: { slug: 'samsung-55-qled-tv' },
      update: {},
      create: {
        name: 'Samsung 55" QLED 4K Smart TV',
        slug: 'samsung-55-qled-tv',
        sku: 'SAMS-TV55-001',
        description: '55-inch Quantum HDR 4K Smart TV with Tizen OS.',
        shortDescription: 'QLED, 4K, 120Hz, Quantum HDR 20+.',
        price: 899.99,
        comparePrice: 999.99,
        costPrice: 600.0,
        stock: 45,
        categoryId: parents[7].id,
        brandId: brands[1].id,
        status: 'ACTIVE',
        isFeatured: true,
        publishedAt: new Date(),
      },
    }),
    prisma.product.upsert({
      where: { slug: 'canon-eos-r6-mark-ii' },
      update: {},
      create: {
        name: 'Canon EOS R6 Mark II',
        slug: 'canon-eos-r6-mark-ii',
        sku: 'CANO-R6M2-001',
        description: 'Full-frame mirrorless camera with 40fps burst.',
        shortDescription: '24.2MP, 40fps, dual card slots, 6K RAW video.',
        price: 2499.99,
        comparePrice: 2699.99,
        costPrice: 1750.0,
        stock: 35,
        categoryId: children[6].id,
        brandId: brands[16].id,
        status: 'ACTIVE',
        publishedAt: new Date(),
      },
    }),
    prisma.product.upsert({
      where: { slug: 'gopro-hero-12' },
      update: {},
      create: {
        name: 'GoPro HERO12 Black',
        slug: 'gopro-hero-12',
        sku: 'GOPO-H12B-001',
        description: 'Waterproof action camera with 5.3K60 video.',
        shortDescription: '5.3K60 HDR video, HyperSmooth 6.0, waterproof 33ft.',
        price: 349.99,
        comparePrice: 399.99,
        costPrice: 200.0,
        stock: 180,
        categoryId: children[7].id,
        brandId: brands[18].id,
        status: 'ACTIVE',
        publishedAt: new Date(),
      },
    }),
    prisma.product.upsert({
      where: { slug: 'anker-140w-charger' },
      update: {},
      create: {
        name: 'Anker 140W USB-C Charger',
        slug: 'anker-140w-charger',
        sku: 'ANKR-140W-001',
        description: 'Compact 140W GaN charger for MacBook Pro.',
        shortDescription: '140W GaN, 3 ports, foldable plug.',
        price: 59.99,
        comparePrice: 79.99,
        costPrice: 25.0,
        stock: 800,
        categoryId: children[8].id,
        brandId: brands[14].id,
        status: 'ACTIVE',
        publishedAt: new Date(),
      },
    }),
    prisma.product.upsert({
      where: { slug: 'jbl-charge-5' },
      update: {},
      create: {
        name: 'JBL Charge 5',
        slug: 'jbl-charge-5',
        sku: 'JBL-CHG5-001',
        description: 'Portable Bluetooth speaker with power bank.',
        shortDescription: 'IP67, 20hr battery, USB-C power bank.',
        price: 179.99,
        comparePrice: 199.99,
        costPrice: 90.0,
        stock: 250,
        categoryId: parents[2].id,
        brandId: brands[9].id,
        status: 'ACTIVE',
        publishedAt: new Date(),
      },
    }),
    prisma.product.upsert({
      where: { slug: 'google-pixel-8-pro' },
      update: {},
      create: {
        name: 'Google Pixel 8 Pro',
        slug: 'google-pixel-8-pro',
        sku: 'GOOG-P8P-001',
        description: "Google's most capable phone with Tensor G3.",
        shortDescription: 'Tensor G3, 50MP triple camera, 7yr updates.',
        price: 999.99,
        comparePrice: 1099.99,
        costPrice: 700.0,
        stock: 100,
        categoryId: children[0].id,
        brandId: brands[13].id,
        status: 'ACTIVE',
        publishedAt: new Date(),
      },
    }),
    prisma.product.upsert({
      where: { slug: 'lenovo-thinkpad-x1-carbon' },
      update: {},
      create: {
        name: 'Lenovo ThinkPad X1 Carbon Gen 11',
        slug: 'lenovo-thinkpad-x1-carbon',
        sku: 'LENO-X1C11-001',
        description: 'Ultra-light business laptop for professionals.',
        shortDescription: 'Intel Core i7, 16GB RAM, 1TB SSD, 2.8K OLED.',
        price: 1749.99,
        comparePrice: 1999.99,
        costPrice: 1200.0,
        stock: 70,
        categoryId: children[3].id,
        brandId: brands[6].id,
        status: 'ACTIVE',
        publishedAt: new Date(),
      },
    }),
    prisma.product.upsert({
      where: { slug: 'asus-rog-zephyrus-g16' },
      update: {},
      create: {
        name: 'ASUS ROG Zephyrus G16',
        slug: 'asus-rog-zephyrus-g16',
        sku: 'ASUS-RZG16-001',
        description: 'Slim gaming powerhouse with RTX 4090.',
        shortDescription: 'Intel Core i9, RTX 4090, 240Hz OLED, 90Wh battery.',
        price: 2999.99,
        comparePrice: 3299.99,
        costPrice: 2100.0,
        stock: 40,
        categoryId: children[2].id,
        brandId: brands[7].id,
        status: 'ACTIVE',
        publishedAt: new Date(),
      },
    }),
    prisma.product.upsert({
      where: { slug: 'xiaomi-redmi-note-13' },
      update: {},
      create: {
        name: 'Xiaomi Redmi Note 13 Pro',
        slug: 'xiaomi-redmi-note-13',
        sku: 'XIAO-RN13P-001',
        description: 'Value flagship with 200MP camera.',
        shortDescription: '200MP camera, Snapdragon 7s Gen 2, 5100mAh.',
        price: 349.99,
        comparePrice: 399.99,
        costPrice: 200.0,
        stock: 300,
        categoryId: children[0].id,
        brandId: brands[19].id,
        status: 'ACTIVE',
        publishedAt: new Date(),
      },
    }),
    prisma.product.upsert({
      where: { slug: 'samsung-galaxy-buds3-pro' },
      update: {},
      create: {
        name: 'Samsung Galaxy Buds3 Pro',
        slug: 'samsung-galaxy-buds3-pro',
        sku: 'SAMS-GB3P-001',
        description: 'Pro-grade sound with intelligent ANC.',
        shortDescription: 'ANC, 360 Audio, IP57, 6hr battery.',
        price: 229.99,
        comparePrice: 249.99,
        costPrice: 120.0,
        stock: 220,
        categoryId: children[5].id,
        brandId: brands[1].id,
        status: 'ACTIVE',
        publishedAt: new Date(),
      },
    }),
    prisma.product.upsert({
      where: { slug: 'microsoft-surface-pro-9' },
      update: {},
      create: {
        name: 'Microsoft Surface Pro 9',
        slug: 'microsoft-surface-pro-9',
        sku: 'MSFT-SP9-001',
        description: '2-in-1 laptop and tablet with Intel Core i7.',
        shortDescription: 'Intel Core i7, 16GB RAM, 256GB SSD, 13" PixelSense.',
        price: 1299.99,
        comparePrice: 1499.99,
        costPrice: 900.0,
        stock: 55,
        categoryId: children[3].id,
        brandId: brands[12].id,
        status: 'ACTIVE',
        publishedAt: new Date(),
      },
    }),
    prisma.product.upsert({
      where: { slug: 'hp-spectre-x360' },
      update: {},
      create: {
        name: 'HP Spectre x360 14"',
        slug: 'hp-spectre-x360',
        sku: 'HP-SPX360-001',
        description: 'Premium convertible laptop with OLED touch display.',
        shortDescription: 'Intel Core Ultra 7, 32GB RAM, 2TB SSD, 2.8K OLED.',
        price: 1799.99,
        comparePrice: 1999.99,
        costPrice: 1250.0,
        stock: 50,
        categoryId: children[3].id,
        brandId: brands[5].id,
        status: 'ACTIVE',
        publishedAt: new Date(),
      },
    }),
  ]);

  console.log(`✓ ${products.length} products seeded`);
  return products;
}
