import { PrismaClient } from '../../generated/prisma/client';

export async function seedCoupons(prisma: PrismaClient) {
  const coupons = await Promise.all([
    prisma.coupon.upsert({
      where: { code: 'WELCOME10' },
      update: {},
      create: {
        code: 'WELCOME10',
        description: '10% off for new customers',
        type: 'PERCENTAGE',
        value: 10,
        minPurchase: 50,
        usageLimit: 1000,
        perUserLimit: 1,
        isActive: true,
        startsAt: new Date('2024-01-01'),
        expiresAt: new Date('2026-12-31'),
      },
    }),
    prisma.coupon.upsert({
      where: { code: 'SAVE20' },
      update: {},
      create: {
        code: 'SAVE20',
        description: '20% off sitewide',
        type: 'PERCENTAGE',
        value: 20,
        minPurchase: 100,
        maxDiscount: 200,
        usageLimit: 500,
        perUserLimit: 1,
        isActive: true,
        startsAt: new Date('2025-01-01'),
        expiresAt: new Date('2025-12-31'),
      },
    }),
    prisma.coupon.upsert({
      where: { code: 'FLAT50' },
      update: {},
      create: {
        code: 'FLAT50',
        description: '$50 off orders over $300',
        type: 'FIXED_AMOUNT',
        value: 50,
        minPurchase: 300,
        usageLimit: 200,
        isActive: true,
      },
    }),
    prisma.coupon.upsert({
      where: { code: 'FREESHIP' },
      update: {},
      create: {
        code: 'FREESHIP',
        description: 'Free shipping on all orders',
        type: 'FREE_SHIPPING',
        value: 0,
        isActive: true,
        usageLimit: 10000,
      },
    }),
    prisma.coupon.upsert({
      where: { code: 'SUMMER25' },
      update: {},
      create: {
        code: 'SUMMER25',
        description: '25% off summer sale',
        type: 'PERCENTAGE',
        value: 25,
        minPurchase: 150,
        maxDiscount: 150,
        usageLimit: 300,
        isActive: true,
        startsAt: new Date('2025-06-01'),
        expiresAt: new Date('2025-08-31'),
      },
    }),
    prisma.coupon.upsert({
      where: { code: 'TECH100' },
      update: {},
      create: {
        code: 'TECH100',
        description: '$100 off electronics over $800',
        type: 'FIXED_AMOUNT',
        value: 100,
        minPurchase: 800,
        usageLimit: 100,
        isActive: true,
      },
    }),
    prisma.coupon.upsert({
      where: { code: 'FLASH15' },
      update: {},
      create: {
        code: 'FLASH15',
        description: '15% flash sale',
        type: 'PERCENTAGE',
        value: 15,
        usageLimit: 50,
        isActive: false,
        expiresAt: new Date('2025-01-01'),
      },
    }),
    prisma.coupon.upsert({
      where: { code: 'VIP30' },
      update: {},
      create: {
        code: 'VIP30',
        description: '30% off for VIP members',
        type: 'PERCENTAGE',
        value: 30,
        minPurchase: 200,
        maxDiscount: 300,
        perUserLimit: 2,
        isActive: true,
      },
    }),
    prisma.coupon.upsert({
      where: { code: 'BACK2SCHOOL' },
      update: {},
      create: {
        code: 'BACK2SCHOOL',
        description: 'Back to school discount',
        type: 'PERCENTAGE',
        value: 12,
        minPurchase: 100,
        usageLimit: 500,
        isActive: true,
      },
    }),
    prisma.coupon.upsert({
      where: { code: 'BLACKFRIDAY' },
      update: {},
      create: {
        code: 'BLACKFRIDAY',
        description: 'Black Friday deal',
        type: 'PERCENTAGE',
        value: 40,
        minPurchase: 500,
        maxDiscount: 400,
        usageLimit: 200,
        isActive: false,
        expiresAt: new Date('2025-11-30'),
      },
    }),
    prisma.coupon.upsert({
      where: { code: 'CYBER50' },
      update: {},
      create: {
        code: 'CYBER50',
        description: 'Cyber Monday $50 off',
        type: 'FIXED_AMOUNT',
        value: 50,
        minPurchase: 250,
        usageLimit: 300,
        isActive: false,
      },
    }),
    prisma.coupon.upsert({
      where: { code: 'REFER20' },
      update: {},
      create: {
        code: 'REFER20',
        description: 'Referral bonus 20% off',
        type: 'PERCENTAGE',
        value: 20,
        perUserLimit: 1,
        isActive: true,
      },
    }),
    prisma.coupon.upsert({
      where: { code: 'LOYALTY15' },
      update: {},
      create: {
        code: 'LOYALTY15',
        description: 'Loyalty reward 15% off',
        type: 'PERCENTAGE',
        value: 15,
        minPurchase: 75,
        isActive: true,
      },
    }),
    prisma.coupon.upsert({
      where: { code: 'MOBILE10' },
      update: {},
      create: {
        code: 'MOBILE10',
        description: '10% off mobile app orders',
        type: 'PERCENTAGE',
        value: 10,
        usageLimit: 2000,
        isActive: true,
      },
    }),
    prisma.coupon.upsert({
      where: { code: 'STUDENT20' },
      update: {},
      create: {
        code: 'STUDENT20',
        description: '20% student discount',
        type: 'PERCENTAGE',
        value: 20,
        minPurchase: 50,
        perUserLimit: 3,
        isActive: true,
      },
    }),
    prisma.coupon.upsert({
      where: { code: 'HOLIDAY25' },
      update: {},
      create: {
        code: 'HOLIDAY25',
        description: 'Holiday season 25% off',
        type: 'PERCENTAGE',
        value: 25,
        minPurchase: 200,
        maxDiscount: 250,
        usageLimit: 400,
        isActive: true,
      },
    }),
    prisma.coupon.upsert({
      where: { code: 'NEWUSER5' },
      update: {},
      create: {
        code: 'NEWUSER5',
        description: '$5 off first order',
        type: 'FIXED_AMOUNT',
        value: 5,
        minPurchase: 20,
        perUserLimit: 1,
        usageLimit: 5000,
        isActive: true,
      },
    }),
    prisma.coupon.upsert({
      where: { code: 'BUNDLE200' },
      update: {},
      create: {
        code: 'BUNDLE200',
        description: '$200 off bundles over $1500',
        type: 'FIXED_AMOUNT',
        value: 200,
        minPurchase: 1500,
        usageLimit: 50,
        isActive: true,
      },
    }),
    prisma.coupon.upsert({
      where: { code: 'EARLYBIRD' },
      update: {},
      create: {
        code: 'EARLYBIRD',
        description: 'Early bird pre-order 18% off',
        type: 'PERCENTAGE',
        value: 18,
        usageLimit: 100,
        isActive: true,
      },
    }),
    prisma.coupon.upsert({
      where: { code: 'GAMERS35' },
      update: {},
      create: {
        code: 'GAMERS35',
        description: '35% off gaming category',
        type: 'PERCENTAGE',
        value: 35,
        minPurchase: 100,
        maxDiscount: 200,
        usageLimit: 150,
        isActive: true,
      },
    }),
  ]);

  console.log(`✓ ${coupons.length} coupons seeded`);
  return coupons;
}
