import {
  PrismaClient,
  User,
  Product,
  Address,
  // PaymentMethod,
} from '../../generated/prisma/client';

type OrderDef = {
  user: User;
  addr: Address;
  product: Product;
  qty: number;
  price: number;
  subtotal: number;
  shipping: number;
  tax: number;
  total: number;
  status:
    | 'PENDING'
    | 'PROCESSING'
    | 'SHIPPED'
    | 'DELIVERED'
    | 'CANCELLED'
    | 'REFUNDED';
  paymentStatus:
    | 'PENDING'
    | 'PAID'
    | 'FAILED'
    | 'REFUNDED'
    | 'PARTIALLY_REFUNDED';
  fulfillmentStatus:
    | 'UNFULFILLED'
    | 'PARTIALLY_FULFILLED'
    | 'FULFILLED'
    | 'RETURNED';
  shippingMethod: 'STANDARD' | 'EXPRESS' | 'OVERNIGHT';
  paidAt?: Date;
  shippedAt?: Date;
  deliveredAt?: Date;
  cancelledAt?: Date;
};

export async function seedOrders(
  prisma: PrismaClient,
  customers: User[],
  products: Product[],
  addresses: Address[],
  // paymentMethods: PaymentMethod[],
) {
  const defs: OrderDef[] = [
    {
      user: customers[0],
      addr: addresses[0],
      product: products[0],
      qty: 1,
      price: 999.99,
      subtotal: 999.99,
      shipping: 0,
      tax: 84.99,
      total: 1084.98,
      status: 'DELIVERED',
      paymentStatus: 'PAID',
      fulfillmentStatus: 'FULFILLED',
      shippingMethod: 'STANDARD',
      paidAt: new Date('2025-01-05'),
      shippedAt: new Date('2025-01-06'),
      deliveredAt: new Date('2025-01-10'),
    },
    {
      user: customers[1],
      addr: addresses[1],
      product: products[1],
      qty: 1,
      price: 1199.99,
      subtotal: 1199.99,
      shipping: 0,
      tax: 101.99,
      total: 1301.98,
      status: 'DELIVERED',
      paymentStatus: 'PAID',
      fulfillmentStatus: 'FULFILLED',
      shippingMethod: 'EXPRESS',
      paidAt: new Date('2025-01-08'),
      shippedAt: new Date('2025-01-09'),
      deliveredAt: new Date('2025-01-11'),
    },
    {
      user: customers[2],
      addr: addresses[2],
      product: products[2],
      qty: 1,
      price: 349.99,
      subtotal: 349.99,
      shipping: 0,
      tax: 29.74,
      total: 379.73,
      status: 'SHIPPED',
      paymentStatus: 'PAID',
      fulfillmentStatus: 'PARTIALLY_FULFILLED',
      shippingMethod: 'STANDARD',
      paidAt: new Date('2025-01-12'),
      shippedAt: new Date('2025-01-13'),
    },
    {
      user: customers[3],
      addr: addresses[3],
      product: products[3],
      qty: 1,
      price: 2499.99,
      subtotal: 2499.99,
      shipping: 0,
      tax: 212.49,
      total: 2712.48,
      status: 'PROCESSING',
      paymentStatus: 'PAID',
      fulfillmentStatus: 'UNFULFILLED',
      shippingMethod: 'OVERNIGHT',
      paidAt: new Date('2025-01-15'),
    },
    {
      user: customers[4],
      addr: addresses[4],
      product: products[4],
      qty: 1,
      price: 1999.99,
      subtotal: 1999.99,
      shipping: 14.99,
      tax: 170.0,
      total: 2184.98,
      status: 'DELIVERED',
      paymentStatus: 'PAID',
      fulfillmentStatus: 'FULFILLED',
      shippingMethod: 'EXPRESS',
      paidAt: new Date('2025-01-18'),
      shippedAt: new Date('2025-01-19'),
      deliveredAt: new Date('2025-01-21'),
    },
    {
      user: customers[5],
      addr: addresses[5],
      product: products[5],
      qty: 2,
      price: 99.99,
      subtotal: 199.98,
      shipping: 5.99,
      tax: 17.0,
      total: 222.97,
      status: 'DELIVERED',
      paymentStatus: 'PAID',
      fulfillmentStatus: 'FULFILLED',
      shippingMethod: 'STANDARD',
      paidAt: new Date('2025-01-20'),
      shippedAt: new Date('2025-01-21'),
      deliveredAt: new Date('2025-01-26'),
    },
    {
      user: customers[6],
      addr: addresses[6],
      product: products[6],
      qty: 1,
      price: 229.99,
      subtotal: 229.99,
      shipping: 0,
      tax: 19.55,
      total: 249.54,
      status: 'CANCELLED',
      paymentStatus: 'REFUNDED',
      fulfillmentStatus: 'UNFULFILLED',
      shippingMethod: 'STANDARD',
      cancelledAt: new Date('2025-01-22'),
    },
    {
      user: customers[7],
      addr: addresses[7],
      product: products[7],
      qty: 1,
      price: 249.99,
      subtotal: 249.99,
      shipping: 0,
      tax: 21.25,
      total: 271.24,
      status: 'DELIVERED',
      paymentStatus: 'PAID',
      fulfillmentStatus: 'FULFILLED',
      shippingMethod: 'EXPRESS',
      paidAt: new Date('2025-01-25'),
      shippedAt: new Date('2025-01-26'),
      deliveredAt: new Date('2025-01-28'),
    },
    {
      user: customers[8],
      addr: addresses[8],
      product: products[8],
      qty: 1,
      price: 899.99,
      subtotal: 899.99,
      shipping: 29.99,
      tax: 78.2,
      total: 1008.18,
      status: 'DELIVERED',
      paymentStatus: 'PAID',
      fulfillmentStatus: 'FULFILLED',
      shippingMethod: 'OVERNIGHT',
      paidAt: new Date('2025-02-01'),
      shippedAt: new Date('2025-02-02'),
      deliveredAt: new Date('2025-02-03'),
    },
    {
      user: customers[9],
      addr: addresses[9],
      product: products[9],
      qty: 1,
      price: 2499.99,
      subtotal: 2499.99,
      shipping: 0,
      tax: 212.49,
      total: 2712.48,
      status: 'PROCESSING',
      paymentStatus: 'PAID',
      fulfillmentStatus: 'UNFULFILLED',
      shippingMethod: 'STANDARD',
      paidAt: new Date('2025-02-05'),
    },
    {
      user: customers[10],
      addr: addresses[10],
      product: products[10],
      qty: 2,
      price: 349.99,
      subtotal: 699.98,
      shipping: 0,
      tax: 59.5,
      total: 759.48,
      status: 'DELIVERED',
      paymentStatus: 'PAID',
      fulfillmentStatus: 'FULFILLED',
      shippingMethod: 'STANDARD',
      paidAt: new Date('2025-02-08'),
      shippedAt: new Date('2025-02-09'),
      deliveredAt: new Date('2025-02-15'),
    },
    {
      user: customers[11],
      addr: addresses[11],
      product: products[11],
      qty: 3,
      price: 59.99,
      subtotal: 179.97,
      shipping: 0,
      tax: 15.29,
      total: 195.26,
      status: 'DELIVERED',
      paymentStatus: 'PAID',
      fulfillmentStatus: 'FULFILLED',
      shippingMethod: 'STANDARD',
      paidAt: new Date('2025-02-10'),
      shippedAt: new Date('2025-02-11'),
      deliveredAt: new Date('2025-02-16'),
    },
    {
      user: customers[12],
      addr: addresses[12],
      product: products[12],
      qty: 1,
      price: 179.99,
      subtotal: 179.99,
      shipping: 5.99,
      tax: 15.8,
      total: 201.78,
      status: 'SHIPPED',
      paymentStatus: 'PAID',
      fulfillmentStatus: 'PARTIALLY_FULFILLED',
      shippingMethod: 'STANDARD',
      paidAt: new Date('2025-02-12'),
      shippedAt: new Date('2025-02-13'),
    },
    {
      user: customers[13],
      addr: addresses[13],
      product: products[13],
      qty: 1,
      price: 999.99,
      subtotal: 999.99,
      shipping: 0,
      tax: 84.99,
      total: 1084.98,
      status: 'PENDING',
      paymentStatus: 'PENDING',
      fulfillmentStatus: 'UNFULFILLED',
      shippingMethod: 'EXPRESS',
    },
    {
      user: customers[14],
      addr: addresses[14],
      product: products[14],
      qty: 1,
      price: 1749.99,
      subtotal: 1749.99,
      shipping: 0,
      tax: 148.75,
      total: 1898.74,
      status: 'DELIVERED',
      paymentStatus: 'PAID',
      fulfillmentStatus: 'FULFILLED',
      shippingMethod: 'STANDARD',
      paidAt: new Date('2025-02-20'),
      shippedAt: new Date('2025-02-21'),
      deliveredAt: new Date('2025-02-26'),
    },
    {
      user: customers[0],
      addr: addresses[0],
      product: products[15],
      qty: 1,
      price: 2999.99,
      subtotal: 2999.99,
      shipping: 0,
      tax: 254.99,
      total: 3254.98,
      status: 'DELIVERED',
      paymentStatus: 'PAID',
      fulfillmentStatus: 'FULFILLED',
      shippingMethod: 'OVERNIGHT',
      paidAt: new Date('2025-03-01'),
      shippedAt: new Date('2025-03-02'),
      deliveredAt: new Date('2025-03-03'),
    },
    {
      user: customers[1],
      addr: addresses[1],
      product: products[16],
      qty: 1,
      price: 349.99,
      subtotal: 349.99,
      shipping: 5.99,
      tax: 30.24,
      total: 386.22,
      status: 'REFUNDED',
      paymentStatus: 'REFUNDED',
      fulfillmentStatus: 'RETURNED',
      shippingMethod: 'STANDARD',
      paidAt: new Date('2025-03-05'),
      shippedAt: new Date('2025-03-06'),
      deliveredAt: new Date('2025-03-11'),
    },
    {
      user: customers[2],
      addr: addresses[2],
      product: products[17],
      qty: 2,
      price: 229.99,
      subtotal: 459.98,
      shipping: 0,
      tax: 39.1,
      total: 499.08,
      status: 'DELIVERED',
      paymentStatus: 'PAID',
      fulfillmentStatus: 'FULFILLED',
      shippingMethod: 'EXPRESS',
      paidAt: new Date('2025-03-10'),
      shippedAt: new Date('2025-03-11'),
      deliveredAt: new Date('2025-03-13'),
    },
    {
      user: customers[3],
      addr: addresses[3],
      product: products[18],
      qty: 1,
      price: 1299.99,
      subtotal: 1299.99,
      shipping: 0,
      tax: 110.49,
      total: 1410.48,
      status: 'PROCESSING',
      paymentStatus: 'PAID',
      fulfillmentStatus: 'UNFULFILLED',
      shippingMethod: 'STANDARD',
      paidAt: new Date('2025-03-15'),
    },
    {
      user: customers[4],
      addr: addresses[4],
      product: products[19],
      qty: 1,
      price: 1799.99,
      subtotal: 1799.99,
      shipping: 14.99,
      tax: 154.25,
      total: 1969.23,
      status: 'SHIPPED',
      paymentStatus: 'PAID',
      fulfillmentStatus: 'PARTIALLY_FULFILLED',
      shippingMethod: 'EXPRESS',
      paidAt: new Date('2025-03-18'),
      shippedAt: new Date('2025-03-19'),
    },
  ];

  const orders = await Promise.all(
    defs.map((def, i) =>
      prisma.order.upsert({
        where: { orderNumber: `ORD-2025-${String(i + 1).padStart(5, '0')}` },
        update: {},
        create: {
          orderNumber: `ORD-2025-${String(i + 1).padStart(5, '0')}`,
          userId: def.user.id,
          shippingAddressId: def.addr.id,
          billingAddressId: def.addr.id,
          subtotal: def.subtotal,
          discount: 0,
          shipping: def.shipping,
          tax: def.tax,
          total: def.total,
          status: def.status,
          paymentStatus: def.paymentStatus,
          fulfillmentStatus: def.fulfillmentStatus,
          shippingMethod: def.shippingMethod,
          paidAt: def.paidAt ?? null,
          shippedAt: def.shippedAt ?? null,
          deliveredAt: def.deliveredAt ?? null,
          cancelledAt: def.cancelledAt ?? null,
          items: {
            create: {
              productId: def.product.id,
              name: def.product.name,
              sku: def.product.sku,
              price: def.price,
              quantity: def.qty,
            },
          },
        },
      }),
    ),
  );

  console.log(`✓ ${orders.length} orders seeded`);
  return { orders, defs };
}
